### ISSUE TITLE
Moving to new weather api.

### ISSUE THREAD

**Issue by eightpage772773** [pendragons-code/Personal-Site#1]
https://rapidapi.com/weatherapi/api/weatherapi-com

this api allows us to get around the call limit, giving us more than enough at the free tier.

**Comment by pendragons-code** [comment]
Update, the new weather API is now possibly not a good alternative. It would seem that it does not pinpoint the specific areas of singapore. TBF it is free so I'm not gonna make a whole lot of demands. Therefor, I will stick to the current system and make some modifications. To how weather and stuff gets generated.
